<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="ask">
	<h3><?php _e('List of questions and answers') ?></h3>
	<table id="question-list" class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Type'); ?></th>
			<th><?php _e('Create'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($questions as $question) { ?>
		<?php
		if($question['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}
		if($question['type'] == 'Q') {
			$labelTypeClass = 'label-primary';
			$titleType = __('Question');
		} elseif($question['type'] == 'A') {
			$labelTypeClass = 'label-danger';
			$titleType = __('Answer');
		}			
		?>
		<tr>
			<td><span id="label-<?php echo $question['id']; ?>" class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($question['id']); ?></span></td>
			<td>
				<?php if(!empty($question['url'])) { ?>
				<a title="<?php echo $this->escape($question['title']); ?>" href="<?php echo $question['url']; ?>">
					<?php echo $this->escape($question['title']); ?>
				</a>
				<?php } else { ?>
				<?php echo $this->escape($question['title']); ?>
				<?php } ?>
			</td>
			<td><span class="label <?php echo $labelTypeClass; ?>"><?php echo $titleType; ?></span></td>
			<td><?php echo $this->escape($question['time_create']); ?></td>
			<td>
				<?php if($question['status'] == 1) { ?>
				<button id="button-<?php echo $question['id']; ?>" type="button" class="btn btn-warning btn-xs" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $question['id'], 'status' => '2')); ?>"><i class="fa fa-times"></i> <?php _e('Reject'); ?></button>
				<?php } else { ?>
				<button id="button-<?php echo $question['id']; ?>" type="button" class="btn btn-success btn-xs" data-toggle="button" data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $question['id'], 'status' => '1')); ?>"><i class="fa fa-check"></i> <?php _e('Accept'); ?></button>
				<?php } ?>
                <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $question['id'])); ?>"><i class="fa fa-pencil-square-o"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $question['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
	<p>
		<span class="label label-success"><?php _e('Published'); ?></span>
		<span class="label label-warning"><?php _e('Pending review'); ?></span>
	</p>
</div>
<script type="text/javascript" >
(function($){
    $("#question-list").on("click","button",function(){
        systemMessage.wait("<?php _e('Accept in process'); ?>");
        $.getJSON($(this).attr("data-link")).done(function(result){
            if(result.ajaxstatus==1){
          	    if(result.questionstatus==1){
	          	    var labelClass = 'label label-success';
	          	    var buttonClass = 'btn btn-warning btn-xs disabled';
	          	    var buttonText = '<i class="fa fa-trash-o"></i> <?php _e("Reject"); ?>';
          	    }
          	    if(result.questionstatus==2){
	          	    var labelClass = 'label label-warning';
	          	    var buttonClass = 'btn btn-success btn-xs disabled';
	          	    var buttonText = '<i class="fa fa-check"></i> <?php _e("Accept"); ?>';
          	    }
          	    $('#label-' + result.id).attr('class', labelClass);
          	    $('#button-' + result.id).attr('class', buttonClass).html(buttonText);;
                systemMessage.succ(result.message);
            }else{
                systemMessage.fail(result.message);
            }
        });
    });
})(jQuery)
</script>