<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix">
    <?php if (!empty($questions)) { ?>
        <h3><?php _e('List of questions and answers') ?></h3>
        <table id="question-list" class="table table-striped table-bordered table-sm">
            <tr>

                <th class="col-md-6"><?php _e('Title'); ?></th>
                <th class="col-md-1"><?php _e('User'); ?></th>
                <th class="col-md-2"><?php _e('Create'); ?></th>
                <th class="col-md-3"><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($questions as $question) { ?>
                <?php if ($question['type'] == 'Q') {
                    $labelTypeClass = 'label-success';
                    $titleType = __('Question');
                } elseif ($question['type'] == 'A') {
                    $labelTypeClass = 'label-info';
                    $titleType = __('Answer');
                } ?>
                <tr>
                    <td>
                        <span class="label <?php echo $labelTypeClass; ?>"><?php echo $titleType; ?></span>
                        <?php if ($question['type'] == 'Q') { ?>
                            <a target="_blank" data-toggle="tooltip" data-placement="top"
                               title="<?php echo $this->escape($question['title']); ?>"
                               href="<?php echo $question['questionUrl']; ?>">
                                <?php echo $this->escape($question['title']); ?>
                            </a>
                        <?php } else { ?>
                            <span data-toggle="tooltip" data-placement="top"
                                  title="<?php echo $this->escape($question['title']); ?>">
                                <?php echo $this->escape($question['title']); ?>
                            </span>
                        <?php } ?>
                    </td>
                    <td>
                        <a target="_blank" href="<?php echo $this->escape($question['user_url']); ?>">
                            <?php echo $this->escape($question['user']['name']); ?>
                        </a>
                    </td>
                    <td><?php echo $this->escape($question['time_create_view']); ?></td>
                    <td>
                        <?php if ($question['status'] == 1) { ?>
                            <button id="button-<?php echo $question['id']; ?>" type="button"
                                    class="btn btn-warning btn-sm" data-toggle="button"
                                    data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $question['id'], 'status' => '2')); ?>">
                                <i class="fa fa-times"></i> <?php _e('Reject'); ?></button>
                        <?php } elseif ($question['status'] == 2) { ?>
                            <button id="button-<?php echo $question['id']; ?>" type="button"
                                    class="btn btn-success btn-sm" data-toggle="button"
                                    data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $question['id'], 'status' => '1')); ?>">
                                <i class="fa fa-check"></i> <?php _e('Accept'); ?></button>
                        <?php } ?>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array('action' => 'update', 'id' => $question['id'])); ?>"><i
                                    class="fa fa-pencil-square-o"></i> <?php _e('Edit'); ?></a>
                        <a class="btn btn-danger btn-sm" title="<?php _e('Delete'); ?>"
                           href="<?php echo $this->url('', array('action' => 'delete', 'id' => $question['id'])); ?>"><i
                                    class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
        <p>
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert"><?php _e('No question submit yet'); ?></div>
    <?php } ?>
</div>
<script type="text/javascript">
    (function ($) {
        $('[data-toggle="tooltip"]').tooltip()
        $("#question-list").on("click", "button", function () {
            systemMessage.wait("<?php _e('Accept in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.questionstatus == 1) {
                        var labelClass = 'badge badge-success';
                        var buttonClass = 'btn btn-warning btn-sm disabled';
                        var buttonText = '<i class="fa fa-trash-o"></i> <?php _e("Reject"); ?>';
                    }
                    if (result.questionstatus == 2) {
                        var labelClass = 'badge badge-warning';
                        var buttonClass = 'btn btn-success btn-sm disabled';
                        var buttonText = '<i class="fa fa-check"></i> <?php _e("Accept"); ?>';
                    }
                    $('#label-' + result.id).attr('class', labelClass);
                    $('#button-' + result.id).attr('class', buttonClass).html(buttonText);
                    ;
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>