<?php 
	$this->css($this->assetModule('css/front.css'));
	if (!empty($vote)) {
		$this->jQuery();
		$this->js($this->assetModule('script/plus.js', 'vote'));
	}
 ?>
<div class="ask">
   <div class="question-title">
	   <h3><?php echo $this->escape($question['title']); ?></h3>
   </div>
   <div class="question-content">
      <div class="span1">
      <?php if (!empty($vote)) { ?>
      <?php $voteClass = 'btn-group-vertical'; ?>
      <?php include $this->template('module/vote:front/votebar'); ?>
      <?php } ?>
      </div>
      <div class="span11">
	      <div class="question-text"><?php echo $question['content']; ?></div>
	      <?php if($tags) { ?>
			<div class="tagbar">
			<?php foreach($tags as $tag) { ?>
				<a title="<?php echo $tag; ?>" href="<?php echo $this->url('.ask', array('module' => $module, 'controller' => 'tag', 'alias' => urlencode($tag))); ?>"><span class="label label-inverse icon-tag"> <?php echo $tag; ?></span></a>
			<?php } ?>
			</div>
			<?php } ?>
      </div>
      <div class="question-author pull-right"><?php echo $this->escape($question['create']); ?> <?php _e('By'); ?> <?php echo $this->escape($question['identity']); ?></div>
	   <div class="clearfix"></div>
   </div>
   <?php if(!empty($answers)) { ?>
   <h4 class="page-header"><?php _e('List of answers'); ?></h4>
   <div class="answer-list">
   <?php foreach($answers as $answer) { ?>
	   <div class="question page-header">
		   <div class="question-body">
			   <div class="question-content">
				   <div class="span1">
               <?php if (!empty($vote)) { ?>
					<?php $vote = $answer['vote']; ?>
					<?php $voteClass = 'btn-group-vertical'; ?>
				   <?php include $this->template('module/vote:front/votebar'); ?>
					<?php } ?>				   
				   </div>
				   <div class="span11">
					   <div class="question-text"><?php echo $answer['content']; ?></div>
				   </div>
			   </div>
			   <div class="question-author pull-right"><?php echo $this->escape($answer['create']); ?> <?php _e('By'); ?> <?php echo $this->escape($answer['identity']); ?></div>
			   <div class="clearfix"></div>
			</div>
		   <div class="clearfix"></div>
		</div>
   <?php } ?>
   <div class="clearfix"></div>
   </div>
   <?php } ?>
   <div class="btn-group"><a class="btn" title="<?php _e('Answers'); ?>" href="<?php echo $this->url('.ask', array('module' => $module, 'controller' => 'answer', 'question' => $question['id'])); ?>"><?php _e('Answers'); ?></a></div>
</div>