<div class="clearfix">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title"><?php echo $this->escape($question['title']); ?></h3>
		</div>
		<div class="panel-body">
			<?php echo $question['content']; ?>
			<div class="clearfix">
				<div class="pull-left"><?php echo $this->escape($question['time_create_view']); ?></div>
			</div>
		</div>
	</div>
	<?php if (isset($answers) && !empty($answers)) { ?>
	<div class="list-group">
		<?php foreach($answers as $answer) { ?>
		<div class="list-group-item">
			<h4 class="list-group-item-heading"><?php echo $this->escape($answer['title']); ?></h4>
			<div class="list-group-item-text">
				<?php echo $answer['content']; ?>
				<div class="clearfix">
					<div class="pull-left"><?php echo $this->escape($answer['time_create_view']); ?></div>
				</div>
			</div>
		</div>
		<?php } ?>
    </div>
    <?php } ?>
    <p><a class="btn btn-primary" title="<?php _e('Answer'); ?>" href="<?php echo $this->url('', array('controller' => 'answer', 'action' => 'index', 'slug' => $this->escape($question['slug']))); ?>"><?php _e('Answer'); ?></a></p>
</div>