<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <?php if (isset($project) && !empty($project)) { ?>
        <div class="page-header clearfix">
            <h1 class="pull-left"><?php echo $this->escape($project['title']); ?></h1>
            <?php if ($config['question_ask']) { ?>
                <p class="pull-right">
                    <a class="btn btn-primary btn-xs" title="<?php _e('Ask question'); ?>" href="<?php echo Pi::url($this->url('', array(
                        'controller' => 'submit',
                        'action' => 'index',
                        'slug' => $project['slug']
                    ))); ?>"><?php _e('Ask question'); ?></a>
                </p>
            <?php } ?>
        </div>
        <div class="clearfix">
            <?php echo $project['text_description']; ?>
        </div>
        <?php echo Pi::api('doc','media')->getSingleLinkUrl($project['main_image'])->thumb('thumbnail'); ?>
    <?php } else { ?>
        <div class="page-header clearfix">
            <h1 class="pull-left"><?php echo $this->escape($title); ?></h1>
            <?php if ($config['question_ask']) { ?>
                <p class="pull-right">
                    <a class="btn btn-primary btn-xs" title="<?php _e('Ask question'); ?>" href="<?php echo Pi::url($this->url('', array(
                        'controller' => 'submit',
                        'action' => 'index'
                    ))); ?>"><?php _e('Ask question'); ?></a>
                </p>
            <?php } ?>
        </div>
    <?php } ?>
    <div class="question-list clearfix">
        <?php foreach($questions as $question) { ?>
            <div class="question-single clearfix">
                <div class="col-md-2">
                    <div class="question-single-information">
                        <ul class="list-inline">
                            <li class="text-center">
                                <?php echo _number($question['answer']) ?>
                                <br />
                                <?php _e('Answer'); ?>
                            </li>
                            <li class="text-center">
                                <?php echo _number($question['hits']) ?>
                                <br />
                                <?php _e('View'); ?>
                            </li>
                            <?php if ($config['vote_bar']) { ?>
                                <li class="text-center">
                                    <?php echo _number($question['point']) ?>
                                    <br />
                                    <?php _e('Vote'); ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
                <div class="col-md-9 clearfix">
                    <div class="question-single-title">
                        <h3>
                            <a title="<?php echo $this->escape($question['title']); ?>" href="<?php echo $question['questionUrl']; ?>">
                                <?php echo $this->escape($question['title']); ?>
                            </a>
                        </h3>
                    </div>
                    <div class="question-single-time">
                        <ul class="list-inline pull-right small">
                            <li><?php _e('On'); ?></li>
                            <li><?php echo $this->escape($question['time_create_view']); ?></li>
                            <li><?php _e('By'); ?></li>
                            <li><?php echo $this->escape($question['user']['name']); ?></li>
                        </ul>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>