<div class="clearfix">
	<div class="page-header">
		<h1><?php echo $this->escape($question['title']); ?></h1>
	</div>
	<div class="clearfix">
        <?php echo $question['text_description']; ?>
    </div>
	<div class="clearfix">
        <?php if ($config['show_info']) { ?>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<ul class="list-inline">
				<li><i class="fa fa-clock-o"></i> <?php _e('Time'); ?>: <?php echo $this->escape($question['time_create_view']); ?></li>
				<li><i class="fa fa-eye"></i> <?php _e('Read'); ?>: <?php echo _number($this->escape($question['hits'])); ?> <?php _e('Times'); ?></li>
			</ul>
		</div>
        <?php } ?>
		<?php if (isset($question['tag']) && !empty($question['tag'])) { ?>
		<div class="tagList col-md-6 col-sm-12 col-xs-12">
			<?php foreach($question['tag'] as $tag) { ?>
			<span class="tagItem">
				<a title="<?php echo $this->escape($tag['term']); ?>" href="<?php echo $this->escape($tag['url']); ?>">
					<i class="fa fa-tag"></i> <?php echo $this->escape($tag['term']); ?>
				</a>
			</span>
			<?php } ?>
		</div>
		<?php } ?>
	</div>
	<?php if (isset($answers) && !empty($answers)) { ?>
	<div class="list-group">
		<?php foreach($answers as $answer) { ?>
		<div class="list-group-item">
			<h4 class="list-group-item-heading"><?php echo $this->escape($answer['title']); ?></h4>
			<div class="list-group-item-text">
				<?php echo $answer['text_description']; ?>
				<div class="clearfix">
					<div class="pull-right"><?php echo $this->escape($answer['time_create_view']); ?></div>
				</div>
			</div>
		</div>
		<?php } ?>
    </div>
    <?php } ?>
    <?php if ($config['question_answer']) { ?>
    <p>
    	<a class="btn btn-primary" title="<?php _e('Answer'); ?>" href="<?php echo $this->url('', array('controller' => 'answer', 'action' => 'index', 'slug' => $this->escape($question['slug']))); ?>"><?php _e('Answer'); ?></a>
    </p>
    <?php } ?>
</div>