CREATE TABLE `{question}` (
	`id` int(10) unsigned NOT NULL auto_increment,
	`type` enum('Q','A') NOT NULL default 'Q',
	`pid` int(10) unsigned NOT NULL default '0',
	`answer` smallint(5) unsigned NOT NULL default '0',
	`uid` int(10) unsigned NOT NULL default '0',
	`point` int(10) NOT NULL default '0',
	`count` int(10) unsigned NOT NULL default '0',
	`favorite` int(10) unsigned NOT NULL default '0',
	`hits` int(10) unsigned NOT NULL default '0',
	`status` tinyint(1) unsigned NOT NULL default '0',
	`time_create` int(10) unsigned NOT NULL default '0',
	`time_update` int(10) unsigned NOT NULL default '0',
	`title` varchar(255) NOT NULL default '',
    `slug` varchar(255) NOT NULL default '',
	`content` text,
	`tag` varchar(255) NOT NULL default '',
	`seo_title` varchar(255) NOT NULL default '',
	`seo_keywords` varchar(255) NOT NULL default '',
	`seo_description` varchar(255) NOT NULL default '',
	PRIMARY KEY (`id`),
	UNIQUE KEY `slug` (`slug`),
	KEY `title` (`title`),
	KEY `status` (`status`),
	KEY `time_create` (`time_create`),
	KEY `hits` (`hits`),
	KEY `point` (`point`),
	KEY `uid` (`uid`),
	KEY `question_list` (`status`, `type`),
	KEY `answer_list` (`status`, `pid`, `type`),
	KEY `submit_list` (`status`, `type`, `title`),
	KEY `author_list` (`status`, `type`, `uid`),
	KEY `order_id` (`time_create`, `id`),
	KEY `order_point` (`point`, `id`),
	KEY `order_hits` (`hits`, `id`),
	KEY `order_answer` (`answer`, `id`)
);