CREATE TABLE `{question}` (
	`id` int(10) unsigned NOT NULL auto_increment,
	`type` enum('Q','A') NOT NULL,
	`pid` int(10) unsigned NOT NULL,
	`answer` smallint(5) unsigned NOT NULL,
	`uid` int(10) unsigned NOT NULL,
	`point` int(10) NOT NULL,
	`count` int(10) unsigned NOT NULL,
	`favorite` int(10) unsigned NOT NULL,
	`hits` int(10) unsigned NOT NULL,  
	`status` tinyint(1) unsigned NOT NULL,
	`time_create` int(10) unsigned NOT NULL,
	`time_update` int(10) unsigned NOT NULL,
	`title` varchar(255) NOT NULL, 
	`slug` varchar(255),
	`content` text,
	`tags` varchar(255) NOT NULL,
	`seo_title` varchar(255) NOT NULL,
	`seo_keywords` varchar(255) NOT NULL,
	`seo_description` varchar(255) NOT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `slug` (`slug`),
	KEY `title` (`title`),
	KEY `status` (`status`),
	KEY `time_create` (`time_create`),
	KEY `hits` (`hits`),
	KEY `point` (`point`),
	KEY `uid` (`uid`),
	KEY `question_list` (`status`, `type`),
	KEY `answer_list` (`status`, `pid`, `type`),
	KEY `submit_list` (`status`, `type`, `title`),
	KEY `author_list` (`status`, `type`, `uid`),
	KEY `order_id` (`time_create`, `id`),
	KEY `order_point` (`point`, `id`),
	KEY `order_hits` (`hits`, `id`),
	KEY `order_answer` (`answer`, `id`)
);